language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install pytest
script: py.test
deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: SBuGrBeAZZvIiY7/WM7lgS9L/A6d27IXcuPFfBzcpgAPTbBFSNOLuj9abQzjEyvCBVjB7TVkXpaEI6NpSF7rLxFMREpWHVNArC3mtPTDf8mRd68jrGKe1FAj+U5GlQbUGIYgSr4F9UHwNX16ru26hJalP7vqAKPNjdGSbHCIR2A=
  strategy: git
  app: lr-team-dashboard
  on:
    repo: LandRegistry/team-dashboard
    branch: master
